// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFud5Kr13xsfzWhB_cPFjCewzhuy--xbw',
    appId: '1:538899056544:android:51886dc6b0413fb88e86c5',
    messagingSenderId: '538899056544',
    projectId: 'eyetruck-driver',
    storageBucket: 'eyetruck-driver.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClKCZQsaXxr9cojvWcFT_ji9FCrsDh500',
    appId: '1:538899056544:ios:4aadb6f420e44ae28e86c5',
    messagingSenderId: '538899056544',
    projectId: 'eyetruck-driver',
    storageBucket: 'eyetruck-driver.appspot.com',
    iosBundleId: 'com.example.eyetruckDriver',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbht7oiCgnSfJI6gPBsZQ1-VKK6lbInmQ',
    appId: '1:538899056544:web:f656d2cd38b0e6988e86c5',
    messagingSenderId: '538899056544',
    projectId: 'eyetruck-driver',
    authDomain: 'eyetruck-driver.firebaseapp.com',
    storageBucket: 'eyetruck-driver.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClKCZQsaXxr9cojvWcFT_ji9FCrsDh500',
    appId: '1:538899056544:ios:4aadb6f420e44ae28e86c5',
    messagingSenderId: '538899056544',
    projectId: 'eyetruck-driver',
    storageBucket: 'eyetruck-driver.appspot.com',
    iosBundleId: 'com.example.eyetruckDriver',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbht7oiCgnSfJI6gPBsZQ1-VKK6lbInmQ',
    appId: '1:538899056544:web:e55765bdd8d5a5e08e86c5',
    messagingSenderId: '538899056544',
    projectId: 'eyetruck-driver',
    authDomain: 'eyetruck-driver.firebaseapp.com',
    storageBucket: 'eyetruck-driver.appspot.com',
  );

}